---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  username: dilaaaap
  env: test
  name: dilaaaap-test-redis-pvc
  app: dilaaaap-test-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
