---
apiVersion: v1
kind: Service
metadata:
  name: dilaaap-service
spec:
  type: ClusterIP
  selector:
    app: dilaaaap-test-redis
  ports:
  - name: dilaaaapservicedeployment
    port: 6410
    targetPort: 6410
